[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
framework = espidf
monitor_speed = 115200

[env:esp32s3]
board = esp32-s3-devkitm-1
upload_protocol = esp-builtin

[env:esp32]
board = esp32dev
